#!/usr/bin/env bash
# Bootstrap devops-control on a production server.
#
# Usage:
#   bash <(curl -fsSL https://raw.githubusercontent.com/sauraku/devops/main/deploy/bootstrap.sh)
#
# Before running, make sure Docker is authenticated to ghcr.io with a PAT:
#   echo <token> | docker login ghcr.io -u sauraku --password-stdin
set -euo pipefail

IMAGE="${IMAGE:-ghcr.io/sauraku/devops:main}"
CONTAINER="${CONTAINER:-devops-control}"
DATA_DIR="${DATA_DIR:-/opt/devops-control}"
ENV_FILE="${ENV_FILE:-/opt/devops-control/.env.prod}"
HOST_PORT="${HOST_PORT:-8787}"
GITHUB_USER="${GITHUB_USER:-sauraku}"

# Login to GHCR using GITHUB_TOKEN env var if set.
# If not set, assumes Docker is already authenticated (e.g. manual docker login).
# Avoids `gh auth token` which may lack read:packages scope.
if [ -n "${GITHUB_TOKEN:-}" ]; then
  echo "==> Logging in to ghcr.io with GITHUB_TOKEN..."
  echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USER" --password-stdin 2>/dev/null || true
fi

# Fall back to user home if /opt is not writable
if [ ! -w "$(dirname "$DATA_DIR")" ] && [ ! -w "$DATA_DIR" ]; then
  DATA_DIR="${HOME}/.devops-control"
  ENV_FILE="${HOME}/.devops-control/.env.prod"
  echo "==> /opt not writable, using $DATA_DIR"
fi

# Auto-create data dir
mkdir -p "$DATA_DIR"

# Check for env file
if [ ! -f "$ENV_FILE" ]; then
  echo "==> No env file found. Generating $ENV_FILE with random secrets..."
  mkdir -p "$(dirname "$ENV_FILE")"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy-devops.sh
DEPLOY_CONTROL_TOKEN=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
COOKIE_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
DEPLOY_CONTROL_HOST=0.0.0.0
BASE_DIR=$DATA_DIR
SSH_HOST=host.docker.internal
EOF
  chmod 600 "$ENV_FILE"
  echo "    Secrets written to $ENV_FILE"
elif ! grep -q "^BASE_DIR=" "$ENV_FILE"; then
  echo "==> Adding BASE_DIR to existing env file"
  echo "BASE_DIR=$DATA_DIR" >> "$ENV_FILE"
fi
if ! grep -q "^SSH_HOST=" "$ENV_FILE"; then
  echo "==> Adding SSH_HOST to existing env file"
  echo "SSH_HOST=host.docker.internal" >> "$ENV_FILE"
fi

# Persist GITHUB_TOKEN into env file if provided at bootstrap time
if [ -n "${GITHUB_TOKEN:-}" ] && ! grep -q "^GITHUB_TOKEN=" "$ENV_FILE" 2>/dev/null; then
  echo "==> Persisting GITHUB_TOKEN to env file"
  echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> "$ENV_FILE"
fi

echo "==> Pulling image: $IMAGE"
docker pull "$IMAGE"

echo "==> Stopping existing container (if any)"
docker stop "$CONTAINER" 2>/dev/null || true
docker rm "$CONTAINER" 2>/dev/null || true

echo "==> Starting devops-control"
docker run -d \
  --name "$CONTAINER" \
  --restart unless-stopped \
  --pull never \
  --add-host host.docker.internal:host-gateway \
  -e "BASE_DIR=$DATA_DIR" \
  -e SSH_HOST=host.docker.internal \
  -e SSH_DIR="$HOME/.ssh" \
  -e GITHUB_TOKEN="${GITHUB_TOKEN:-}" \
  --env-file "$ENV_FILE" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$DATA_DIR":"$DATA_DIR" \
  -v "$HOME/.ssh":"$HOME/.ssh":ro \
  -p "${HOST_PORT}:8787" \
  "$IMAGE"

echo "==> Done. Container: $CONTAINER"
echo "    Logs: docker logs -f $CONTAINER"
echo "    Token: saved in $ENV_FILE"
echo "    Login at http://<host>:${HOST_PORT}"
echo "    To update later, run the same command again."
