#!/usr/bin/env bash
# Local dev start script — ALWAYS rebuilds the binary and UI.
# For production, use ./start.sh (requires pre-built binary + .env.prod).
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

# ── Gather what we need ──────────────────────────────────────────────
ENV_FILE="$DIR/.env.local"
if [ -f "$ENV_FILE" ]; then
  set -a
  source "$ENV_FILE"
  set +a
fi

if [ -z "${DEPLOY_CONTROL_TOKEN:-}" ]; then
  read -rsp "Enter a deploy control token: " DEPLOY_CONTROL_TOKEN
  echo
  export DEPLOY_CONTROL_TOKEN
fi

if [ -z "${GITHUB_TOKEN:-}" ]; then
  read -rsp "Enter a GitHub PAT (ghp_...) for runner registration [optional]: " GITHUB_TOKEN
  echo
  export GITHUB_TOKEN
fi

if [ -z "${JWT_SECRET:-}" ]; then
  JWT_SECRET="$(openssl rand -hex 32)"
  export JWT_SECRET
fi

if [ -z "${COOKIE_SECRET:-}" ]; then
  COOKIE_SECRET="$(openssl rand -hex 32)"
  export COOKIE_SECRET
fi

if [ -z "${ENCRYPTION_KEY:-}" ]; then
  ENCRYPTION_KEY="$(openssl rand -hex 32)"
  export ENCRYPTION_KEY
fi

if [ -z "${BASE_DIR:-}" ]; then
  DEFAULT_DIR="$DIR/data"
  read -rp "Project base directory [${DEFAULT_DIR}]: " BASE_DIR
  BASE_DIR="${BASE_DIR:-$DEFAULT_DIR}"
  export BASE_DIR
fi

mkdir -p "$BASE_DIR"

# ── Persist secrets ────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by local.sh — do not commit
JWT_SECRET=$JWT_SECRET
COOKIE_SECRET=$COOKIE_SECRET
ENCRYPTION_KEY=$ENCRYPTION_KEY
DEPLOY_CONTROL_TOKEN=$DEPLOY_CONTROL_TOKEN
DEPLOY_CONTROL_HOST=${DEPLOY_CONTROL_HOST:-0.0.0.0}
BASE_DIR=$BASE_DIR
EOF
if [ -n "${GITHUB_TOKEN:-}" ]; then
  echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> "$ENV_FILE"
fi
chmod 600 "$ENV_FILE"

# ── Build (always rebuild UI + Go) ───────────────────────────────────
BINARY="$DIR/devops-control"
echo "==> Building UI ..."
(cd "$DIR/ui" && npm install --silent && npm run build) || {
  echo "!! Frontend build failed but the backend will still work."
  echo "   The API will run — just open http://localhost:8787/api/health"
}
echo "==> Building Go binary ..."
go build -o "$BINARY" ./cmd/devops-control/
echo "==> Build done."

# ── Start ────────────────────────────────────────────────────────────
echo ""

# Tear down any existing process on port 8787 (local dev only)
PORT_PID=$(lsof -ti :8787 2>/dev/null || true)
if [ -n "${PORT_PID:-}" ]; then
  echo "==> Killing existing process on port 8787 (pid=$PORT_PID)"
  kill -9 $PORT_PID 2>/dev/null || true
  sleep 0.3
fi

echo "==> Starting DevOps Control on http://localhost:8787"
echo "    Data:  $BASE_DIR"
echo "    PID:   $$"
echo ""

exec "$BINARY"
